import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome' });
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
const errs=[]; p.on('pageerror', e=>errs.push(String(e)));
await p.goto('https://mango-signal-map.vercel.app/', { waitUntil: 'networkidle', timeout: 60000 });
await p.evaluate(()=>localStorage.clear()); await p.reload({waitUntil:'networkidle'});
await p.waitForTimeout(3000);
console.log('01 标题:', await p.locator('#prefs h2').innerText());
await p.locator('#prefs button').first().click();
await p.waitForTimeout(1500); await p.mouse.click(800,500); await p.waitForTimeout(3500);
console.log('偏好选项:', await p.locator('#prefs button[class*="chip"]').count());
console.log('圈层卡:', await p.locator('#targets article').count(), '| 名单卡:', await p.locator('#list article').count());
const first = await p.locator('#list article').first().innerText();
console.log('名单第一位:', first.replace(/\n+/g,' | ').slice(0,110));
const tags = await p.locator('#list article span[class*="srcTag"]').allTextContents();
console.log('前 10 个标记:', tags.slice(0,10).join(' '));
console.log('右栏:', await p.locator('aside[data-screen-label="实时反馈"]').count()>0);
console.log('页面错误:', errs.length?errs.slice(0,2):'none');
await b.close();
