import { chromium } from 'playwright-core';
const b = await chromium.launch({ channel: 'chrome' });
const p = await b.newPage({ viewport: { width: 1600, height: 1000 } });
const errs=[]; p.on('pageerror', e=>errs.push(String(e)));
await p.goto('http://127.0.0.1:3100/', { waitUntil: 'domcontentloaded', timeout: 60000 });
await p.evaluate(()=>localStorage.clear()); await p.reload({waitUntil:'domcontentloaded'});
await p.locator('#prefs button').first().waitFor({timeout:40000});
await p.locator('#prefs button').first().click();
await p.waitForTimeout(1300); await p.mouse.click(800,500); await p.waitForTimeout(3000);
const q = await p.locator('#list span[class*="queue"]').allTextContents();
console.log('队列标签样本:', [...new Set(q)].slice(0,5));
const st = await p.locator('#list span[class*="strength"]').allTextContents();
console.log('强度标签:', [...new Set(st)]);
await p.locator('#list').scrollIntoViewIfNeeded(); await p.waitForTimeout(900);
await p.screenshot({ path: 'shots/queue-list.png', timeout: 90000 });
await p.locator('button:has-text("采用这个起点")').click(); await p.waitForTimeout(2500);
await p.locator('#confirm').scrollIntoViewIfNeeded(); await p.waitForTimeout(900);
const blocks = await p.locator('#confirm div[class*="queueHead"]').allTextContents();
console.log('确认区队列分组:', blocks.map(t=>t.replace(/\s+/g,' ').trim()));
await p.screenshot({ path: 'shots/queue-confirm.png', timeout: 90000 });
console.log('页面错误:', errs.length?errs.slice(0,2):'none');
await b.close();
